Change default output size add ability to have custom output size
azureskydiver/Blake3Core pull request #2
Opened 2021-11-22 14:50 UTC by Rudde

I've changed the default output size from 512 to 256 bit per BLAKE3 spec.

I was unsure how to implement support for custom output length, I chose to go about in bits, I don't know if it would be better in bytes? I chose bits as that's usually the number hash algorithms advertise and make themselves known by.

This is just a proposal, please let me know if you'd like anything changed.

2021-11-24 03:32 UTC, azureskydiver requested changes
Thank you very much for pull request. I really appreciate it!

Next time I'll be able to look at the code will likely be Sunday when I start being on the mend after my next chemo session tomorrow.

2021-11-24 03:32 UTC, azureskydiver commented on Blake3Core/Blake3.cs
> +        protected private Blake3(Flag defaultFlag, ReadOnlySpan<uint> key, int? outputSizeInBits)
Why not just use a default parameter value instead of futzing around with a nullable int?

2021-11-24 03:32 UTC, azureskydiver commented on Blake3Core.Tests/Correctness.cs
> +        private const int _defaultOutputByteSize = 32;
Please follow my coding style of not declaring `private`.

2021-11-26 01:24 UTC, Rudde commented
I've done the changes. I'm also curious why sizeof(uint) is used as a const?

2021-12-13 23:01 UTC, Rudde commented
Hey man, I hope your chemo went well. Did you ever get a chance to look at this?

2021-12-15 02:14 UTC, merged